shoc:
  name: shoc 
  vm_groups:
    default:
      vm_spec:
        GCP:
          boot_disk_size: 200
  flag_matrix_defs:
    GCP:
      gce_migrate_on_maintenance: [False]
      image: [ubuntu-1604-xenial-v20161115]
      image_project: [ubuntu-os-cloud]
      machine_type: [
        n1-standard-4-k80x1, n1-standard-8-k80x1, n1-standard-8-k80x2,
        n1-standard-16-k80x2, n1-standard-16-k80x4, n1-standard-32-k80x4,
        n1-standard-32-k80x8
      ]
      zones: [us-east1-d]
    AWS:
      image: [ami-b7a114d7]
      machine_type: [
        p2.xlarge, p2.8xlarge, p2.16xlarge
      ]
      zones: [us-west-2b]
    Azure:
      image: ["Canonical:UbuntuServer:16.04.0-LTS:latest"]
      machine_type: [
        Standard_NC6, Standard_NC12, Standard_NC24
      ]
      zones: [eastus]
cuda_hpl:
  name: cuda_hpl
  vm_groups:
    default:
      vm_spec:
        GCP:
          boot_disk_size: 200
  flag_matrix_defs:
    GCP:
      gce_migrate_on_maintenance: [False]
      image: [/ubuntu-os-cloud/ubuntu-1604-xenial-v20161115]
      machine_type: [
        n1-standard-4-k80x1, n1-standard-8-k80x1, n1-standard-8-k80x2,
        n1-standard-16-k80x2, n1-standard-16-k80x4, n1-standard-32-k80x4,
        n1-standard-32-k80x8
      ]
      zones: [us-east1-d]
    AWS:
      image: [ami-b7a114d7]
      machine_type: [
        p2.xlarge, p2.8xlarge, p2.16xlarge
      ]
      zones: [us-west-2b]
    Azure:
      image: ["Canonical:UbuntuServer:16.04.0-LTS:latest"]
      machine_type: [
        Standard_NC6, Standard_NC12, Standard_NC24
      ]
      zones: [eastus]
gpu_pcie_bandwidth:
  name: gpu_pcie_bandwidth
  vm_groups:
    default:
      vm_spec:
        GCP:
          boot_disk_size: 200
  flag_matrix_defs:
    GCP:
      gce_migrate_on_maintenance: [False]
      image: [/ubuntu-os-cloud/ubuntu-1604-xenial-v20161115]
      machine_type: [
        n1-standard-4-k80x1, n1-standard-8-k80x1, n1-standard-8-k80x2,
        n1-standard-16-k80x2, n1-standard-16-k80x4, n1-standard-32-k80x4,
        n1-standard-32-k80x8
      ]
      zones: [us-east1-d]
    AWS:
      image: [ami-b7a114d7]
      machine_type: [
        p2.xlarge, p2.8xlarge, p2.16xlarge
      ]
      zones: [us-west-2b]
    Azure:
      image: ["Canonical:UbuntuServer:16.04.0-LTS:latest"]
      machine_type: [
        Standard_NC6, Standard_NC12, Standard_NC24
      ]
      zones: [eastus]

